services:
  enter_data:
    build:
      context: ./enter_data
    ports:
      - "5000:5000"
  
  show_results:
    build:
      context: ./show_results
    ports:
      - "5001:5001"

  analytics:
    build:
      context: ./analytics
    ports:
      - "5002:5002"
